### ISSUE TITLE
How to save the decoder.pth of monodepth2

### ISSUE THREAD

**Issue by jzwqaq** [jan9419/ORB_SLAM3_Monodepth#1]
hello, thanks for  your shared code. Its a great work.
I am confused with those words "Furthermore, the decoder in the Monodepth2 repository needs to be modified to return the last tuple element (self.outputs[("disp", 0)])"
I want to know how to get the decoder.pth  from monodepth2, which line to add or modify the code to get the decoder.pth.
Wish you to apply me, thx a lot.

**Comment by jan9419** [comment]
Thank you for your interest in the work.
You can donwload the pre-trained `decoder.pth` models in the Monodepth2 repository.
To embed the pre-trained models into C++ via LibTorch, you have to convert them into TorchScript models. 
Since for tracing (`torch.jit.trace`) output dictionaries with the key type `(str, int)` are not supported the depth decoder (`networks/depth_decoder.py`) in the Monodepth2 repository needs to be adapted. In this project only the last output is needed, so the simplest solution is to return the last element of the dictionary.
So in the Monodepth2 repository in the file `networks/depth_decoder.py` change line 65 from `return self.outputs` to `return self.outputs[("disp", 0)]`. After that execute the script `export_models.py`:
```
python tools/export_models.py --input_encoder_path PATH_TO_MONODEPTH_PRETRAINED_MODEL/encoder.pth --input_decoder_path PATH_TO_MONODEPTH_PRETRAINED_MODEL/decoder.pth --output_encoder_path tools/encoder.pt --output_decoder_path tools/decoder.pt --device cuda
```

**Comment by RoZhong** [comment]
> hello, thanks for your shared code. Its a great work. I am confused with those words "Furthermore, the decoder in the Monodepth2 repository needs to be modified to return the last tuple element (self.outputs[("disp", 0)])" I want to know how to get the decoder.pth from monodepth2, which line to add or modify the code to get the decoder.pth. Wish you to apply me, thx a lot.

Can you share how to do abort these words"Export pre-trained Monodepth2 models (trained on the KITTI dataset) to TorchScript models. For this please add the Monodepth2 repository to the PYTHONPATH environment variable" 
I can not find TorchScript and do not know how to add it to the PythonPath.
Hope your reply.

**Comment by RoZhong** [comment]
> 您好，感谢您的共享代码。它是一部伟大的作品。 我对这些词感到困惑“此外，需要修改 Monodepth2 存储库中的解码器以返回最后一个元组元素 (self.outputs[("disp", 0)])” 我想知道如何获取解码器。 pth from monodepth2，添加或修改代码的哪一行得到decoder.pth。 希望你申请我，谢谢。

Why is there only encoder.pth but not decoder.pth in the model I downloaded? I don't know if you have run it, can you give a more detailed operation process about 4.2, I don't know how to add it to the environment variable, I can only use "sys.path.append" for temporary addition, and the command I don't know what each parameter corresponds to. Can you give me an example so that I can compare and see what file the parameters correspond to?

**Comment by jan9419** [comment]
See issue #2
